server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: cloud
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/picture?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: picture
    password: test
  #    开放更大的文件上传
  servlet:
    multipart:
      max-file-size: 30MB
  redis:
    database: 0
    host: 111.230.167.134
    port: 6379
    timeout: 5000
    password: test

#这一部分的配置可以直接从官网上找
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #日志，我们应该只在开发环境用，这是为了记录我们的输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置，负责定义如何生成主键ID
      id-type: auto
      logic-delete-field: isDelete
      #表示删除的逻辑化数值
      logic-delete-value: 1
      #未删除逻辑化值
      logic-not-delete-value: 0

# 接口文档配置
knife4j:
  basic:
    username: root
    password: test
  # 开启 Knife4j 的增强功能
  enable: true
  # 【关键】关闭生产环境限制，允许在线调试
  production: false
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.et.cloud.controller

# 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://cloud-1380686335.cos.ap-chongqing.myqcloud.com
    secretId: ${COS_SECRET_ID}
    secretKey: ${COS_SECRET_KEY}
    region: ap-chongqing
    bucket: cloud-1380686335
